language: ruby
sudo: false
before_install:
  - gem install bundler:1.17.3
cache: bundler
bundler_args: --without deployment

rvm:
  - 2.2.4
  - 2.3.4
  - 2.4.1
  - 2.5.8
  - 2.7.2

gemfile:
  - gemfiles/4.2.gemfile
  - gemfiles/5.0.gemfile
  - gemfiles/5.1.gemfile
  - gemfiles/6.0.gemfile
  - gemfiles/6.1.gemfile
  - gemfiles/7.0.gemfile

jobs:
  exclude:
    - rvm: 2.2.4
      gemfile: gemfiles/6.0.gemfile
    - rvm: 2.3.4
      gemfile: gemfiles/6.0.gemfile
    - rvm: 2.4.1
      gemfile: gemfiles/6.0.gemfile
    - rvm: 2.2.4
      gemfile: gemfiles/6.1.gemfile
    - rvm: 2.3.4
      gemfile: gemfiles/6.1.gemfile
    - rvm: 2.4.1
      gemfile: gemfiles/6.1.gemfile
    - rvm: 2.2.4
      gemfile: gemfiles/7.0.gemfile
    - rvm: 2.3.4
      gemfile: gemfiles/7.0.gemfile
    - rvm: 2.4.1
      gemfile: gemfiles/7.0.gemfile
    - rvm: 2.5.8
      gemfile: gemfiles/7.0.gemfile